# `async/await`

`async/await` — це синтаксичний цукор для промісів, який дозволяє працювати з асинхронним кодом у більш зрозумілому і схожому на синхронний способі.

## `async`

Ключове слово `async` використовується для оголошення функції як асинхронної. Якщо функція оголошена з використанням `async`, то вона завжди повертає проміс, навіть якщо її тіло не містить ключового слова `return`. Це дає можливість використовувати await всередині функції.

```js
async function myFunction() {
    // Асинхронний код
}

const myFunction = async () => {
    // Асинхронний код
};
```

Результатом виконання двох функцій стане новий проміс. Ми лише додали одне ключове слово і отримали проміс. Якщо застосовувати проміси, то нам довелося б скористатися конструктором або виконати `resolve`.

## `await`

Ключове слово `await` використовується всередині асинхронної функції для очікування результату виконання проміса. Воно показує JavaScript-у, що код наступного рядка повинен бути виконаний тільки після того, як проміс буде виконаний або відхилений. Коли `await` використовується з промісом, воно блокує виконання коду у даній функції до тих пір, поки проміс не буде вирішено.

```js
async function myFunction() {
    const result = await promise;
    // Далі йде код, який виконується після виконання проміса
}
```

`await` можна використовувати тільки всередині асинхронних функцій, оголошених з використанням `async`. Це дозволяє писати асинхронний код, який виглядає подібно до синхронного і має послідовну структуру.

## Обробка помилок

Щоб обробити помилки при використанні `async/await`, можна використовувати блок `try/catch`. Код, який може призвести до помилки, обертається в блок `try`, а код для обробки помилки — в блок `catch`.

```js
async function myFunction() {
    try {
        const result = await promise;
        // Код, який виконується після виконання проміса
    } catch (error) {
        // Обробка помилки
    }
}
```

Якщо проміс, на який застосовується await, буде відхилений, керування передається в блок `catch`, де можна обробити помилку.

**Приклад**

```js
const TIMEOUT = 1000;

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const buyProducts = async () => {
    console.log("> Йду за продуктами");

    await delay(TIMEOUT);

    const products = ["Капуста", "Картопля", "М'ясо"];
    return products;
};

const prepareProducts = async (products) => {
    console.log(`> Ріжу продукти: ${products.join(`, `)}`);

    await delay(TIMEOUT);

    console.log("> Продукти нарізані!");
};

const makeSoup = async (preparedProducts) => {
    console.log(`> Починаю варити суп з: ${products.join(`, `)}`);

    await delay(TIMEOUT);

    const ok = Math.random() > 0.5;
    if (!ok) return Promise.reject("> Ой! Зламалась плита.");

    return "> Суп готовий!";
};

(async () => {
    try {
        const products = await buyProducts();
        await prepareProducts(products);
        const result = await makeSoup(products);
        console.log(result);
    } catch (error) {
        console.log(error);
    }
})();
```
